# Generated by Django 5.1.4 on 2025-03-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_rutas_delete_monitoreodispositivo_rutadispositivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRutaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivos_con_error', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_ruta_dispositivo',
                'managed': False,
            },
        ),
    ]
